### ISSUE TITLE
Split out read-only parts of ITenantProvider

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Tenancy#138]
We expect many consumers of tenancy to be interested only in reading tenant information. Currently, the only abstraction available for fetching tenancy information is `ITenantProvider`, which also provides the abililty to modify tenants.

We are effectively replicating the mistake the .NET Framework made of not defining read-only collection interfaces up front, with the effect that it's generally impossible to tell whether something asked for an `IList<T>` because it intends to modify the list, or simply because its design comes from an era before `IReadOnlyList<T>` was an option (or indeed because the author didn't think to use `IReadOnlyList<T>` but probably should have).;

We should provide a read-only alternative to `ITenantProvider`. (E.g., `ITenantReader`.)

**Comment by mwadams** [comment]
100% agree with this.

**Comment by mwadams** [comment]
`ITenantProvider` feels like the read only version and `ITenantSomethingElse` feels like the writeable version.

**Comment by idg10** [comment]
Resolved by #140
