### ISSUE TITLE
It's currently not possible to use Corvus.Tenancy in conjunction with key rotation

### ISSUE THREAD

**Issue by jongeorge1** [corvus-dotnet/Corvus.Tenancy#164]
Our tenanted storage factory classes generally return the underlying storage mechanism from their respective APIs - e.g. the tenanted Cosmos factory returns a `Container`, blob storage returns a `CloudBlobContainer`, etc.

As a result, it's not possible for us to implement key rotation as part of this library. However, it's also not possible for something using this library to implement key rotation because once we've detected that a key has changed (likely as a result of a Forbidden result from the underlying storage) we have no way of forcing the tenanted storage factories in Corvus.Tenancy to give us a new instance of the underlying container rather than its cached instance.

**Comment by jongeorge1** [comment]
Draft PR #165 shows how this could be achieved. See discussion on that PR for further questions that need to be answered as part of the solution.

**Comment by idg10** [comment]
Resolved by #382
