### ISSUE TITLE
Detect and remove faulted storage instances from caches

### ISSUE THREAD

**Issue by jongeorge1** [corvus-dotnet/Corvus.Tenancy#214]
Apply this fix: https://github.com/corvus-dotnet/Corvus.Tenancy/pull/213 to the other tenanted storage mechanisms (blob, table, SQL) where applicable.

**Comment by jongeorge1** [comment]
This has now been addressed for Blob and Table storage, as well as the Gremlin Client.

It still needs to be fixed for the SQL connection factory.

**Comment by idg10** [comment]
Resolved by #382
