### ISSUE TITLE
Add ability to obtain the name of a specific storage container based on its definition/configuration.

### ISSUE THREAD

**Issue by jongeorge1** [corvus-dotnet/Corvus.Tenancy#282]
Some providers - notably the Azure Storage related ones - create container/table names that are not human-readable. This  makes it difficult to identify which container belongs to a tenant.

**Comment by idg10** [comment]
The actual tool will be built as part of the work under https://github.com/marain-dotnet/Marain.Tenancy/issues/215 but `Corvus.Tenancy` does need to provide a public API for determining the correct name.

**Comment by idg10** [comment]
Addressed by #385
